"""Build tables_for_post.docx -- every table from the analysis, formatted for
embedding into a Medium post (paste, or screenshot the table).

Reads the CSVs written by 04_figures.R. Run from the project root:
    python3 make_tables_docx.py
"""
import csv, os
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

R = "results"
INK = RGBColor(0x1B, 0x1B, 0x1F)
GREY = RGBColor(0x6E, 0x6E, 0x78)
RUST = RGBColor(0xC0, 0x49, 0x2B)


def load(name):
    with open(os.path.join(R, name)) as f:
        return list(csv.DictReader(f))


def shade(cell, hexcolor):
    el = OxmlElement("w:shd")
    el.set(qn("w:val"), "clear")
    el.set(qn("w:fill"), hexcolor)
    cell._tc.get_or_add_tcPr().append(el)


def add_table(doc, number, title, subtitle, headers, rows, widths=None,
              highlight_row=None):
    h = doc.add_paragraph()
    r = h.add_run(f"Table {number}. {title}")
    r.bold = True
    r.font.size = Pt(11)
    r.font.color.rgb = INK
    h.paragraph_format.space_before = Pt(18)
    h.paragraph_format.space_after = Pt(2)

    if subtitle:
        s = doc.add_paragraph()
        rs = s.add_run(subtitle)
        rs.italic = True
        rs.font.size = Pt(8.5)
        rs.font.color.rgb = GREY
        s.paragraph_format.space_after = Pt(6)

    t = doc.add_table(rows=1, cols=len(headers))
    t.style = "Light List Accent 1"
    t.alignment = WD_TABLE_ALIGNMENT.LEFT

    for i, htxt in enumerate(headers):
        c = t.rows[0].cells[i]
        c.text = ""
        run = c.paragraphs[0].add_run(htxt)
        run.bold = True
        run.font.size = Pt(9)
        if i > 0:
            c.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT

    for ri, row in enumerate(rows):
        cells = t.add_row().cells
        for i, val in enumerate(row):
            cells[i].text = ""
            run = cells[i].paragraphs[0].add_run(str(val))
            run.font.size = Pt(9)
            if highlight_row is not None and ri == highlight_row:
                run.bold = True
                run.font.color.rgb = RUST
            if i > 0:
                cells[i].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT
            if highlight_row is not None and ri == highlight_row:
                shade(cells[i], "FBF0EC")

    if widths:
        for row in t.rows:
            for i, w in enumerate(widths):
                row.cells[i].width = Inches(w)
    return t


def note(doc, text):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.font.size = Pt(8)
    r.italic = True
    r.font.color.rgb = GREY
    p.paragraph_format.space_after = Pt(4)


doc = Document()
for s in doc.sections:
    s.left_margin = s.right_margin = Inches(0.8)
normal = doc.styles["Normal"]
normal.font.name = "Calibri"
normal.font.size = Pt(10)

ttl = doc.add_paragraph()
tr = ttl.add_run("Estimating the under-30 share of breast cancer in Bangladesh")
tr.bold = True
tr.font.size = Pt(15)
tr.font.color.rgb = INK
sub = doc.add_paragraph()
sr = sub.add_run("Tables for the Medium post. Generated by 04_figures.R -> "
                 "make_tables_docx.py. Every figure here is reproducible from "
                 "the R scripts in R/.")
sr.italic = True
sr.font.size = Pt(9)
sr.font.color.rgb = GREY

# ---------------------------------------------------------------- Table 1
add_table(
    doc, 1,
    "Three questions that sound like one question",
    "Conflating these is the most common error in reporting rare-disease burden.",
    ["The question", "What it is", "What you need to answer it"],
    [
        ["\"What share of breast cancer patients are under 30?\"",
         "Age distribution among cases",
         "Age composition of diagnosed cases"],
        ["\"What is a young woman's chance of getting it?\"",
         "Age-specific incidence rate",
         "Cases AND a population denominator"],
        ["\"How many under-30 women are diagnosed a year?\"",
         "National count",
         "The share AND the national all-age total"],
    ],
    widths=[2.9, 1.9, 2.2])
note(doc, "A young population produces a young-looking case mix at identical "
          "risk. Reading a high share as high risk mistakes a population "
          "pyramid for a biological finding.")

# ---------------------------------------------------------------- Table 2
st = load("table_studies.csv")
add_table(
    doc, 2,
    "The Bangladeshi hospital evidence",
    "Study sizes are real. Under-30 counts are ILLUSTRATIVE: no published "
    "Bangladeshi series reports a count under 30.",
    ["Source", "Type", "Patients (n)", "Under 30 (x)", "Share"],
    [[r["study"], r["source_type"], r["n"], r["x"],
      f'{100*float(r["p_hat"]):.1f}%'] for r in st]
    + [["Pooled (random effects)", "—", str(sum(int(r["n"]) for r in st)),
        str(sum(int(r["x"]) for r in st)), "5.2%"]],
    widths=[2.6, 1.1, 1.0, 1.0, 0.9],
    highlight_row=len(st))
note(doc, "A mean age of 46.2 is compatible with an under-30 share of 1% or of "
          "10%. Published means cannot be inverted into age-band counts.")

# ---------------------------------------------------------------- Table 3
cov = load("table_coverage.csv")
add_table(
    doc, 3,
    "Precision is not accuracy",
    "Pooling more studies that share the same selection bias. Simulation: true "
    "national share 2%, referral tilt 2.1x, 400 replicates per row.",
    ["Studies pooled", "Chance the 95% interval contains the truth"],
    [[r["k"], f'{100*float(r["coverage"]):.0f}%'] for r in cov],
    widths=[2.0, 3.4])
note(doc, "Sampling error shrinks with more data. Selection bias does not — it "
          "just becomes more precisely wrong.")

# ---------------------------------------------------------------- Table 4
bd = load("table_bounds.csv")
add_table(
    doc, 4,
    "One equation, two unknowns: what the tilt assumption buys",
    "logit(what hospitals see) = logit(national truth) + delta. Every row fits "
    "the hospital data exactly as well as every other row.",
    ["Assumed referral tilt", "National share under 30", "Women per year",
     "Per 100,000 aged 20-29"],
    [[r["assumption"].replace("  ", " ").strip(),
      f'{100*float(r["theta"]):.1f}%',
      f'{float(r["cases"]):.0f}',
      f'{float(r["rate"]):.2f}'] for r in bd],
    widths=[2.6, 1.5, 1.2, 1.4],
    highlight_row=0)
note(doc, "The top row is what naive pooling silently assumes: that published "
          "hospital case series are a random sample of the country.")

# ---------------------------------------------------------------- Table 5
ld = load("table_ladder.csv")
add_table(
    doc, 5,
    "The ladder: what each ingredient is worth",
    "Same data throughout. Only the assumptions change.",
    ["Model", "Share under 30", "95% interval", "National count"],
    [[r["model"].replace("  ", " ").strip(),
      f'{100*float(r["med"]):.1f}%',
      f'{100*float(r["lo"]):.1f}% – {100*float(r["hi"]):.1f}%',
      f'{float(r["cases"]):.0f}'] for r in ld],
    widths=[2.8, 1.2, 1.5, 1.2],
    highlight_row=len(ld) - 1)
note(doc, "Almost all of the movement is in the last row — the one parameter "
          "that no additional Bangladeshi hospital data could ever inform.")

# ---------------------------------------------------------------- Table 6
sn = load("table_sensitivity.csv")
add_table(
    doc, 6,
    "Sensitivity: the assumption, not the data, is in charge",
    "Refitting the full Bayesian model under different prior beliefs about the "
    "referral tilt.",
    ["Prior tilt (odds ratio)", "Posterior share", "95% credible interval",
     "National count"],
    [[f'{float(r["or"]):.1f}x', f'{100*float(r["med"]):.1f}%',
      f'{100*float(r["lo"]):.1f}% – {100*float(r["hi"]):.1f}%',
      f'{float(r["cases"]):.0f}'] for r in sn],
    widths=[1.8, 1.4, 1.7, 1.4])
note(doc, "The answer moves by a factor of roughly four across this range. That "
          "fact is the finding.")

# ---------------------------------------------------------------- Table 7
lo = load("table_loo.csv")
add_table(
    doc, 7,
    "Leave-one-study-out",
    "Refitting the full model with each Bangladeshi study removed in turn.",
    ["Study removed", "Posterior share", "Shift"],
    [[r["dropped"], f'{100*float(r["theta"]):.2f}%',
      f'{float(r["shift_pp"]):+.2f} pp'] for r in lo],
    widths=[3.2, 1.6, 1.4])
note(doc, "No single study drives the estimate. The estimate is driven by the "
          "tilt assumption — which is a more honest thing to depend on, because "
          "it can be argued about in public.")

# ---------------------------------------------------------------- Table 8
add_table(
    doc, 8,
    "The headline, stated the way it deserves to be stated",
    "Model-based estimate. Bangladesh has no population-based cancer registry.",
    ["Quantity", "Estimate"],
    [["Share of breast cancers before age 30 (tilt assumption only)",
      "1.8% – 3.5%"],
     ["Share, also carrying study sampling noise", "1.3% – 4.7%"],
     ["Bayesian posterior share (median, 95% CrI)", "2.0% (1.3% – 3.2%)"],
     ["Women diagnosed before 30 per year (tilt range)", "170 – 334"],
     ["Bayesian posterior count (median, 95% CrI)", "187 (95 – 363)"],
     ["Incidence per 100,000 women aged 20–29", "about 1 – 3"],
     ["Individual annual risk, woman aged 20–29", "roughly 1 in 50,000"],
     ["Posterior referral tilt (odds ratio)", "2.3 (1.5 – 3.4)"]],
    widths=[4.0, 2.2],
    highlight_row=3)
note(doc, "Rare is a rate. Hundreds is a count. Both sentences describe the "
          "same number.")

doc.add_page_break()
p = doc.add_paragraph()
r = p.add_run("Provenance of every input")
r.bold = True
r.font.size = Pt(12)

rg = load("table_registries.csv")
add_table(
    doc, 9,
    "Inputs and how much to trust them",
    "Tags follow 00_inputs.R.",
    ["Input", "Value", "Tag"],
    [["GLOBOCAN 2024, Bangladesh, new female breast cancer cases", "9,480",
      "VERIFIED"],
     ["GLOBOCAN 2024, Bangladesh, breast cancer deaths", "4,211", "VERIFIED"],
     ["GLOBOCAN 2024, Bangladesh, 5-year prevalence", "23,625", "VERIFIED"],
     ["Bangladesh female population, 2024", "88,218,713", "VERIFIED"],
     ["Women aged 20–29 (denominator)", "~15.0 million", "APPROX (UN WPP)"],
     ["Hospital study sizes (n)", "34 / 50 / 276 / …", "VERIFIED for 3 of 6"],
     ["Hospital under-30 counts (x)", "constructed", "ILLUSTRATIVE"],
     ["Regional registry shares under 30",
      ", ".join(f'{100*float(r["share_u30"]):.1f}%' for r in rg), "APPROX"],
     ["Referral tilt prior (odds ratio)", "2.1 (SD 0.24 on log scale)",
      "APPROX"],
     ["Uncertainty on GLOBOCAN's national total", "25% CV", "ASSUMPTION"]],
    widths=[3.4, 1.8, 1.6])
note(doc, "IARC's own incidence footnote for Bangladesh: \"Rates based on "
          "incidence estimates or registry data from neighbouring countries.\" "
          "Its prevalence footnote derives Bangladeshi figures from Nordic "
          "ratios scaled by Human Development Index.")

out = "tables_for_post.docx"
doc.save(out)
print("wrote", out)
